language: rust
arch: arm64
sudo: required
python:
    -"3.6"
rust:
    - stable
    - beta
    - nightly


before_install:
    - apt-cache search musl
    - apt-cache search gnueabihf
    - apt-cache search gcc
    - apt-cache search pyenv
    - rustup self update
    - pyenv install 3.6.3
    - pyenv global 3.6.3
    - python --version
    - pip --version
    - pip install ubus_simulator/.

install:
    - make install
    - cargo install cross
    - rustup target add armv7-unknown-linux-musleabi

script:
    - make test
    - make release
    
matrix:
    allow_failures:
        - rust: nightly
    fast_finish: true

after_failure:
    - apt-cache search musl
    - apt-cache search gnueabihf