language: rust
sudo: required
python:
    -"3.6"
rust:
    - stable
    - beta
    - nightly

before_install:
    
    - rustup self update
    - pyenv install --list
    - pyenv install 3.6.3
    - pyenv global 3.6.3
    - python --version
    - pip --version
    - sudo apt install gcc-8-arm-linux-gnueabihf musl-tools -y
    - pip install ubus_simulator/.


install:
    - make install
    - cargo install cross
    - rustup target add armv7-unknown-linux-musleabi

script:
    - make test
    - make release
    
matrix:
    allow_failures:
        - rust: nightly
    fast_finish: true
