language: rust

arch: arm64

sudo: required

python:
    - 3.7
rust:
    - stable
    - nightly

cache: cargo
env:
    RUST_BACKTRACE=1
addons:
    apt:
        sources:
            - deadsnakes
        packages: &musl_packages
            - musl
            - musl-tools
            - musl-dev
            - gcc-5-arm-linux-gnueabihf
        packages: &python
            - python3.7
            - python3-pip

before_install:
    - python3.7 -m pip install setuptools
    - python3.7 -m pip install ubus_simulator/.
    - python3.7 -m pip install pytest
    - rustup self update
    - python --version
    - pip --version

install:
    - cargo install cross
    - rustup target add armv7-unknown-linux-musleabi

script:
    - python3.7 -m pytest ubus_simulator/
    - make test
    - which musl-gcc
    - make release_travis
    
matrix:
    allow_failures:
        - rust: nightly
    fast_finish: true

after_failure:
    - apt-cache search musl
    - apt-cache search gnueabihf