language: rust
arch: arm64
sudo: required
python:
    -"3.6"
rust:
    - stable
    - beta
    - nightly

addons:
    apt:
        packages: &musl_packages
            - musl-tools
            - gcc-8-arm-linux-gnueabihf
            
before_install:
    
    - rustup self update
    - pyenv install --list
    - pyenv install 3.6.3
    - pyenv global 3.6.3
    - python --version
    - pip --version
    - pip install ubus_simulator/.


install:
    - make install
    - cargo install cross
    - rustup target add armv7-unknown-linux-musleabi

script:
    - make test
    - make release
    
matrix:
    allow_failures:
        - rust: nightly
    fast_finish: true

after_failure:
    - apt-cache search musl
    - apt-cache search gnueabihf