language: rust
arch: arm64
sudo: required
python:
    - 3.7
rust:
    - stable
    - beta
    - nightly

addons:
    apt:
        packages: &musl_packages
            - musl-tools
            - musl
            - gcc-5-arm-linux-gnueabihf

before_install:
    - apt-cache search python
    - rustup self update
    - python --version
    - pip --version
    - pip install ubus_simulator/.

install:
    - make install
    - cargo install cross
    - rustup target add armv7-unknown-linux-musleabi

script:
    - make test
    - make release_travis
    
matrix:
    allow_failures:
        - rust: nightly
    fast_finish: true

after_failure:
    - apt-cache search musl
    - apt-cache search gnueabihf