language: rust
sudo: required
python:
    -"3.6"
rust:
    - stable
    - beta
    - nightly

before_install:
    - rustup self update
    - sudo apt install software-properties-common -y
    - sudo add-apt-repository ppa:deadsnakes/ppa -y
    - sudo apt update -y
    - sudo apt install python3.7 -y
    - sudo apt-get install python3-setuptools python3-pip -y
    - python3 --version

install:
    - pip3 install ubus_simulator/.
    - make install
    - cargo install cross
    - rustup target add armv7-unknown-linux-musleabi

script:
    - make test
    - make release
    
matrix:
    allow_failures:
        - rust: nightly
    fast_finish: true
