language: rust
sudo: required
python:
    -"3.6"
rust:
    - stable
    - beta
    - nightly

before_install:
    - rustup self update
    - pyenv install 3.7.0
    - pyenv global 3.7.0
    - python --version
    - pip --version

install:
    - pip install ubus_simulator/.
    - make install
    - cargo install cross
    - rustup target add armv7-unknown-linux-musleabi

script:
    - make test
    - make release
    
matrix:
    allow_failures:
        - rust: nightly
    fast_finish: true
