language: rust
arch: arm64
sudo: required
python:
    - 3.7
rust:
    - stable
    - beta
    - nightly

addons:
    apt:
        sources:
            - deadsnakes
        packages: &musl_packages
            - musl-tools
            - musl
            - gcc-5-arm-linux-gnueabihf
        packages: &python
            - python3.7
            - python3.7-pip

before_install:
    - python3.7 -m pip install setuptools
    - python 3.7 -m pip install ubus_simulator/.
    - rustup self update
    - python --version
    - pip --version

install:
    - make install
    - cargo install cross
    - rustup target add armv7-unknown-linux-musleabi

script:
    - python 3.7 -m pytest ubus_simulator/
    - make test
    - make release_travis
    
matrix:
    allow_failures:
        - rust: nightly
    fast_finish: true

after_failure:
    - apt-cache search musl
    - apt-cache search gnueabihf